### PR TITLE
MaterialButton Tab Focus

### PR DESCRIPTION
**Pull request by orapps44**
Add focus to MaterialButton when Tab Key is pressed.
Fix Enter KeyDown animation.

### CODE REVIEW

**Comment by valimaties** [comment]
Sorry, but this PR does not do what is intended to do! 
I don't know if you understood what I want with this Focus visibility on `MaterialButton`. What I've did in my PR is what it has to do, Button must have other color than other buttons in form, to be able to see what button has the focus. 
I downloaded this PR, but pressing TAB key will not have a visibility on which button has focus.

**Comment by valimaties** [comment]
I've also wrote some comments on my PR ( #284 )...

**Comment by orapps44** [comment]
Animation

**Comment by valimaties** [comment]
Hi @orapps44 ,

I've tested this PR, and it is not good approach! If you get with mouse over the button, you will lose the focused effect. You will not know which button has the focus. 
I think it is not a good idea to eliminate the focused effect when mouse is leaving the object. I must know in anytime which is the focused button. What will happening if from mistake I will grab mouse over the focused button and leave?! I will not know which is the button which has the focus. 
I consider my approach, having all the time the focus color different than other buttons is better. Maybe not in my approach, using `ControlPaint`, but think of it.
As I can think of, this PR is not helping me. 

BTW: Look how Google implemented focused effect on their buttons:
GoogleApproachForButtons

MouseOver and MouseLeave does not affect focused border...

**Comment by valimaties** [comment]
And BTW, it is not good to force Focus on a object only dragging mouse over it. That is not Focus, that is only hover!

**Comment by orapps44** [comment]
Right, I will rework that.

**Comment by valimaties** [comment]
> Right, I will rework that.

Thanks :)

**Comment by orapps44** [comment]
That should work as expected with last commit.

**Comment by valimaties** [comment]
YEEESSS... This must be quickly merged 💯

**Pull request merged**
