### PR TITLE
Scrollable Drawer on MouseWheel and Click'n'Move implementation

### PR DESCRIPTION
**Pull request by valimaties**
This is based on #236  which is based on #163 . #236 is better coded, as long as it will increments/decrements the `Height` of the drawer (the right divider is higher enough, will not stops when scrolling up, in #163 the divider was shorter and it was shorter when scrolling up).
I removed the `EnableScrolling` property from `MaterialDrawer` control, as long as we need this option all the time. Scrolling option does not affect Drawer as long as its content is not higher than itself.

BTW: Reading Material Design implementation, about showing ScrollBar, (as you @orapps44 asked for in your comment in #236 ) `NavigationDrawer` does not shows any scrollbar when scrolls or when mouse hover. This is the implementation of [Material Design scrolling techniques](https://material.io/archive/guidelines/patterns/scrolling-techniques.html#scrolling-techniques-behavior). It just scrolls container if childs are in the non visible area of control.

Using this technique we can go forward and implement Drawer SubMenu items, as @ryanrox asked for it in #177 or in the latest #293

Demo:
ScrollableDrawer

### CODE REVIEW

**Comment by orapps44** [comment]
That looks good, but it needs to be slightly improved.
Currentely drawer is designed as a form "stciked" to main form. Due to that scrolling only works on drawer if drawer form is focused. 
I expect drawer scrolling to works without need fot user to click on it to get focus.

**Comment by valimaties** [comment]
> That looks good, but it needs to be slightly improved. Currentely drawer is designed as a form "stciked" to main form. Due to that scrolling only works on drawer if drawer form is focused. I expect drawer scrolling to works without need fot user to click on it to get focus.

I don't click on drawer, I click on other objects and mouse over drawer wheel will scroll.

Demo:
ScrollableDrawer2

**Comment by valimaties** [comment]
I've solved some bugs in initial commit, because drawer will not resize correctly when scrolling using MouseWheel.
I've added possibility to scroll drawer by click and move drawer up and down. It will not change the current tab page if it detects that the last click on button was to scroll drawer.

Demo:
ScrollableDrawerWithClickNMove

**Comment by orapps44** [comment]
> I don't click on drawer, I click on other objects and mouse over drawer wheel will scroll.

I've tried it with win 7, I will try again this evening with windows 10.

**Comment by valimaties** [comment]
> > I don't click on drawer, I click on other objects and mouse over drawer wheel will scroll.
> 
> I've tried it with win 7, I will try again this evening with windows 10.

Yes, indeed. I've tried right now in a Virtual W7 environment, and seems wheel scroll does not work until drawer has focus.
But I've made some research and now it is ok. Works even on Windows 7 😊

**Comment by valimaties** [comment]
Seems there are some problems after last commit, it affects form size and other things, like anchor... 
I will make some research to see what is going on... 
So do not merge this...

**Comment by valimaties** [comment]
As long as Windows 7 is out of "service", I propose merging this PR as long as it works on >W7 OS'es. I don't use anymore W& on all my PCs and also,, my clients has upgraded their systems to W10 or W11. 
I think even it is a small problem with WheelScroll on W7, there is Click'n'Move option for scrolling drawer. Personally, I want it to go forward in codding  😚

**Comment by valimaties** [comment]
@orapps44 , could you try it now with commit [b5081e4](https://github.com/leocb/MaterialSkin/pull/306/commits/b5081e48ba71a169c9bf6da8f04ded31fc46da8b) ?

This works for me in W7, W10, on both MaterialExample form and in my other application.

**Comment by valimaties** [comment]
Hi @orapps44 .
Could you try last commit on your side? Windows 7, Windows 10, MaterialSkinExample, your other projects... Works fine on my side, on W7 or greater.

**Comment by orapps44** [comment]
Hi @valimaties ,

I confirm that works fine with W7 & W10.

**Pull request merged**
