### PR TITLE
Add support for Aero Snapping

### PR DESCRIPTION
**Pull request by VolatilePulse**
Provides consistent control positioning by referencing client area instead of form area
Removed unnecessary WndProc code for resizing due to changes
Minimal code cleanup

Fixes maximize bug that allowed "drifting" of the window
Fixes maximize bug that prevented the form from being maximized on a second monitor
Fixes maximize bug that required the program to be maximized prior to snapping maximized

### CODE REVIEW

**Comment by orapps44** [comment]
Thank you @VolatilePulse for this great work.

This code properly fix #84 #215 #219

**Comment by orapps44** [comment]
@VolatilePulse : This PR seems to be root cause of issue #227. 
Any idea what could be wrong ?

**Comment by VolatilePulse** [comment]
Yeah, I just noticed that last night but couldn't identify the cause of the issue. This helps me narrow down what's causing it and allow me to work on a solution. Unfortunately, I'll be out of town until next week.

**Comment by orapps44** [comment]
It seems to be related with WS_SIZEFRAME.

Issue is solved when WS_SIZEFRAME is removed from :

      par.Style = par.Style | WS_MINIMIZEBOX | WS_SYSMENU | WS_SIZEFRAME; // Turn on the WS_MINIMIZEBOX style flag

But without WS_SIZEFRAME, aero snap doesn't work ...

**Comment by VolatilePulse** [comment]
For the time being, this code will suffice for the designer. I'll have to do more investigating once I'm back as information is very limited.
```cs
        protected override CreateParams CreateParams
        {
            get
            {
                var par = base.CreateParams;
                par.Style |= WS_MINIMIZEBOX | WS.WS_SYSMENU;

                if (!DesignMode)
                    par.Style |= WS_SIZEFRAME;

                return par;
            }
        }
```

**Comment by orapps44** [comment]
Hi @VolatilePulse ,

Bug mentioned in #243, seems to be a side effect of this PR.

**Pull request merged**
