### PR TITLE
Added support for "UserControl" Containers

### PR DESCRIPTION
**Pull request by nfasvp**
- Enhancements:
    - Added support for "UserControl" Containers
      - Previous versions only supported placing controls like MaterialDialog if the Parent Container was of a type that inherits from Winform (Form class), like MaterialForm or plain Winform. Adding MaterialDialog control to a custom UserControl would generate a runtime exception because MaterialDialog._formOverlay was expecting an "Onwer" of type "Form" which is not the case when using parent containers like UserControls.
      - Changed class "MaterialDialog" to expect a Parent-container of type "ContainerControl", Form and UserControl classes inherit from ContainControl class.
      - Affected files:
        - MaterialDialog.cs
        - MaterialSkinManager.cs

    - Improved design-mode experience of MaterialDrawer when combined with MaterialTabControl object. Now, during design-time, it's possible to view the drawer and the design impact on it when drawer's and tabcontrol's properties are changed by the user.
        - Design-Mode Before:       
image

        - Design-mode After:
image

    - Improved performance of MaterialDrawer during initialization
      - Reduced the number of "Redraws" (Pain events) while the MaterialDrawer control is being initialized by its container.
        - Previously, during MaterialDrawer's initialization, every property set done by the container that would impact drawer's UI would generate a redraw event (paint event).
        - Now, MaterialDrawer control checks if its container has finished the initialization and if not ignores the redraw. When container invokes control's "InitLayout" method, meaning "end of control's initialization phase, future propertities changes will invoke a redraw action.

### CODE REVIEW

**Comment by orapps44** [comment]
Hi @nfasvp ,

Thank you for your work.

This PR seems somehow allready part of PR #338 , do you confirm ?

**Comment by nfasvp** [comment]
Hi @leocb , yes, this PR contains #338 changes.

**Comment by orapps44** [comment]
Duplicate of #338

**Comment by nfasvp** [comment]
Hi @orapps44, my bad, I wanted to say that PR #338 is part of #339, so #338 is the duplicate, not #339.

**Pull request closed without merging**
