### PR TITLE
Mouse Wheel Drawer Scroll

### PR DESCRIPTION
**Pull request by KristanSmout**
Adds the ability to use the scroll wheel on the app drawer to scroll up and down the icons within it. This can be toggled on the form itself like some of the other drawer options that are currently available keeping this feature as an optional one for only people who need it.

### CODE REVIEW

**Review by KristanSmout — COMMENTED** [review]
Seem to have lots of changes showing just because of the line endings, the actual changes occur in "MaterialDrawer.cs" and "MaterialForm.cs"

**Comment by leocb** [comment]
Please rebase your branch against the latest from master, thanks

**Comment by leocb** [comment]
Hi, Awesome work! please rebase your pull request against the latest from master, thanks!

**Comment by orapps44** [comment]
This feature has been added with PR #306 .

**Pull request closed without merging**
