### PR TITLE
MaterialButton HighlightOnFocus property

### LINKED ISSUE #279: Focused button visibility
Hi,
I'm wondering if someone thought of implementing a "focused color" property in `MaterialButton` control. Textboxes have that animated bottom line which tells you which control has focus, but button have not. 
@orapps44, could you implement a `FocusedForeColor` or `FocusedBackColor` property (or both) on `MaterialButton` to be able to show which button in form has the focus?

Thanks.

### PR DESCRIPTION
**Pull request by valimaties**
Setting this property to `True` will apply a percent of lighting or darker color, based on `Theme` used and type of button. It uses `ControlPaint.Light(Color, percentDarkDark)` or `ColorPaint.Dark(Color, percentDarkDark)` method.
As long as this is a `bool` property and it is not set in `MaterialButton`'s constructor, this PR will not affect any project, by default it is false, the buttons will have old `MaterialSkin` approach.

This will close #279 

Demo:
MaterialButtonHiglight

### CODE REVIEW

**Comment by orapps44** [comment]
Hi @valimaties ,

I see some issues in your PR.

- Adding a property isn't necessary.
- Tab Highlighting is different than mouse over.
- Once highlighted, button will remain highlighted until mouse goes over it (so on same form you may have two highlighted buttons at the same time which is bad.

**Comment by orapps44** [comment]
I've prepared quickly a new PR #285 that basically add this feature with less code modifications. 
Try it and let me know.

**Comment by valimaties** [comment]
Mine works as I expected, I don't know what you are saying about. As it is shown in demo gif, everything works as I expected. But I will try your PR...

**Comment by valimaties** [comment]
I have tried your PR, but it does not do anything! Or you did not understood what FocusVisibility means... Or on my installation simply does not do anything.
Please, could you make a gif or something of what you see on those buttons when you press Tab key? I don't see any change on buttons.

**Pull request closed without merging**
