### PR TITLE
ComboBox.DisplayMember fix. 

### PR DESCRIPTION
**Pull request by AlsDev-Sbin**
#61  ComboBox.DisplayMember fix. NullReference error.

Only two lines were added and adding the **System.Data** reference;

`var table = ((DataRow)Items[e.Index].GetType().GetProperty("Row").GetValue(Items[e.Index])).Table;`
`Text = table.Rows[e.Index][DisplayMember].ToString();`

### CODE REVIEW

**Comment by leocb** [comment]
Hi, sorry, I didn't see your pr before. Does this fix any specific issue?
I review it and merge soon

**Comment by leocb** [comment]
Hi, could you please rebase this fix against the latest from master and resolve the conflicts? thanks!

**Comment by AlsDev-Sbin** [comment]
Yes sure! I'll do it tonight!

________________________________
De: Leo Bottaro ***@***.***>
Enviado: sexta-feira, 7 de maio de 2021 21:06
Para: leocb/MaterialSkin ***@***.***>
Cc: AlsDev ***@***.***>; Author ***@***.***>
Assunto: Re: [leocb/MaterialSkin] ComboBox.DisplayMember fix. (#122)


Hi, could you please rebase this fix against the latest from master and resolve the conflicts? thanks!

**Comment by orapps44** [comment]
Fixed in PR #176

**Pull request closed without merging**
